### ISSUE TITLE
The repository does not get updated :see_no_evil: 

### ISSUE THREAD

**Issue by idriss-dev** [AhmedBoustani/gh-create#5]
I do not have a repository of that name; but still, it does not let me to create the repo

```
donkakashi@DESKTOP-DJGPM6B:~$ gh-create test-repo-from-desktop
Repository (test-repo-from-desktop):
Private (y/N):
Description (): friends's repo

ERROR: Repo was not created.
Tip: Make sure that the name of the repo is unique
```

**Comment by aaBoustani** [comment]
You have the version from the latest commit, right?

**Comment by idriss-dev** [comment]
Yep did only execute 
`wget -O - https://raw.githubusercontent.com/AhmedBoustani/gh-create/master/gh-create > gh-create`

**Comment by aaBoustani** [comment]
That's weird cause I just tried it 4 times and it worked in all four. Make sure that you have the latest version and if you must, recreate the symbolic link

**Comment by idriss-dev** [comment]
![image](https://user-images.githubusercontent.com/6286315/35818823-ea537498-0a98-11e8-9be2-b13a14b56014.png)

**Comment by aaBoustani** [comment]
`sudo ln -sf` to update the existing symbolic link

**Comment by idriss-dev** [comment]
![image](https://user-images.githubusercontent.com/6286315/35820465-99245dda-0a9d-11e8-974c-af9b15eb307b.png)

**Comment by aaBoustani** [comment]
Make sure your token has the right access for creating repos

**Comment by idriss-dev** [comment]
yep, I did not think of that, thanks m8
